### ISSUE TITLE
Occasional error on first run

### ISSUE THREAD

**Issue by prochot** [prochot/USGS-Water-Data#6]
Sometimes encounter an error from SQL Server Management Studio when procedure is first run with new site, or after the connection has been idle for a long time. Executing the procedure again succeeds.

>Msg 6522, Level 16, State 1, Procedure dbo.UspGetUSGSDataBySite, Line 0 [Batch Start Line 2]
A .NET Framework error occurred during execution of user-defined routine or aggregate "UspGetUSGSDataBySite": 
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
System.Net.WebException: 
   at System.Net.HttpWebRequest.GetResponse()
   at StoredProcedures.UspGetUSGSDataBySite(SqlInt32 site)

**Comment by prochot** [comment]
Have not been able to make issue repeatable.

* Opened new instance of SSMS and executed procedure... WebException
* Closed SSMS and opened new instance. Executed procedure again... success

Possibly related to Windows 10 [ClientCacheTime](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn786418(v%3Dws.11)#clientcachetime)?

**Comment by prochot** [comment]
Changed from .Net 4.7.2 to .Net 4.6.2 for compatibility with default Windows Server 2016 installation. Also changed procedure from "Unrestricted" to "External_Access". WebException first execution after publish...

**Comment by prochot** [comment]
Following MS advice found [here](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls), removed line:
'''ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;'''

Now procedure throws error every execution.
Put it back.

**Comment by prochot** [comment]
Tried giving localhost certificate NETWORK SERVICE permissions as per [this](https://stackoverflow.com/a/27302270/11731368) from stackoverflow. No joy.
